// <auto-generated />
namespace Minifutbol.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dbCrete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbCrete));
        
        string IMigrationMetadata.Id
        {
            get { return "201808160837212_dbCrete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
