// <auto-generated />
namespace Minifutbol.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Pointtaleadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pointtaleadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201808150440344_Point tale added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
